version: "3.3"

services:
  mariadb:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: mariadb
    environment:
      - PUID=1000
      - PGID= 1000
      - MYSQL_ROOT_PASSWORD=9501
      - TZ=America/Los_Angeles

    volumes:
      - ./db:/config

    restart: unless-stopped
